- route: /
  name: Home
  controller: Abollinger\Partez\Controller\HomeController

- route: /about
  name: About
  controller: Abollinger\Partez\Controller\AboutController

- route: /admin
  name: Admin
  title: Settings
  controller: Abollinger\Partez\Controller\AdminController
  onNavbar: false
  